{{- if .Values.metricsService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphile-worker.fullname" . }}-metrics
  labels:
    {{- include "graphile-worker.labels" . | nindent 4 }}
    {{- with .Values.metricsService.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - name: metrics
      port: {{ .Values.metricsService.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "graphile-worker.selectorLabels" . | nindent 4 }}
{{- end }}
