apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphile-worker.fullname" . }}
  labels:
    {{- include "graphile-worker.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: health
      port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "graphile-worker.selectorLabels" . | nindent 4 }}
